easy_admin:
    site_name: 'Home'
    formats:
        datetime: 'd/m/Y H:i'
    user:
        name_property_path: 'email'
    entities:
        User:
            class: App\Entity\User
            form:
                fields: ['email']
            new:
                fields:
                    - { property: 'plainPassword', type: 'text', label: 'Password', type_options: { required: true }}
        PelletRecord:
            class: App\Entity\PelletRecord
            list:
                sort: 'date'
        WaterRecord:
            class: App\Entity\WaterRecord
            list:
                sort: 'date'

    design:
        menu:
            - { label: 'Stats', route: 'water_stats', icon: 'pie-chart', params: {'menuIndex': 0} }
            - { entity: WaterRecord, icon: 'tint' }
            - { entity: PelletRecord, icon: 'fire' }
            - { entity: User, icon: 'user' }
